from __future__ import annotations

import time
from pathlib import Path

from app_paths import CACHE_DIR, RUNTIME_ROOT


class CookieFormatError(RuntimeError):
    pass


def prepare_cookie_file(cookie_path: str) -> str:
    path = Path(cookie_path)
    if not path.is_absolute():
        path = RUNTIME_ROOT / path
    if not path.exists():
        raise CookieFormatError(f"Cookie 文件不存在: {path}")

    text = path.read_text(encoding="utf-8-sig", errors="replace")
    if _looks_like_netscape_cookie_file(text):
        return str(path)

    cookies = _parse_raw_cookie_text(text)
    if not cookies:
        raise CookieFormatError(
            "Cookie 文件格式不正确。yt-dlp 需要 Netscape cookies.txt；"
            "也可以在文件中放入浏览器请求头里的 Cookie: name=value; name2=value2。"
        )

    return str(_write_netscape_cookie_file(cookies))


def _looks_like_netscape_cookie_file(text: str) -> bool:
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("# Netscape HTTP Cookie File"):
            return True
        if line.startswith("#"):
            continue
        return len(raw_line.split("\t")) >= 7
    return False


def _parse_raw_cookie_text(text: str) -> list[tuple[str, str]]:
    cookie_text = _extract_cookie_header_value(text)
    cookie_text = cookie_text.replace("\r", "\n").replace("\n", "; ")

    cookies: list[tuple[str, str]] = []
    seen: set[str] = set()
    for part in cookie_text.split(";"):
        item = part.strip()
        if not item or "=" not in item:
            continue
        name, value = item.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name or name.lower() in _NON_COOKIE_HEADER_NAMES:
            continue
        if any(ch.isspace() for ch in name):
            continue
        if name in seen:
            continue
        seen.add(name)
        cookies.append((name, value))
    return cookies


def _extract_cookie_header_value(text: str) -> str:
    cookie_lines: list[str] = []
    capture = False
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        lower = line.lower()
        if lower.startswith("cookie:"):
            capture = True
            cookie_lines.append(line.split(":", 1)[1].strip())
            continue
        if capture and ":" in line and "=" not in line.split(":", 1)[0]:
            break
        cookie_lines.append(line)
    return "\n".join(cookie_lines) if cookie_lines else text


def _write_netscape_cookie_file(cookies: list[tuple[str, str]]) -> Path:
    target_dir = CACHE_DIR / "cookies"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "yt_dlp_cookies.txt"
    expires = int(time.time()) + 365 * 24 * 60 * 60

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Tube_Ultimate_Player from a raw Cookie header.",
    ]
    for name, value in cookies:
        if name.startswith("__Host-"):
            domain = "youtube.com"
            include_subdomains = "FALSE"
            secure = "TRUE"
        else:
            domain = ".youtube.com"
            include_subdomains = "TRUE"
            secure = "TRUE" if name.startswith("__Secure-") else "FALSE"
        clean_value = value.replace("\t", "").replace("\r", "").replace("\n", "")
        lines.append(
            f"{domain}\t{include_subdomains}\t/\t{secure}\t{expires}\t{name}\t{clean_value}"
        )
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


_NON_COOKIE_HEADER_NAMES = {
    "accept",
    "accept-language",
    "cache-control",
    "connection",
    "host",
    "origin",
    "referer",
    "sec-fetch-dest",
    "sec-fetch-mode",
    "sec-fetch-site",
    "user-agent",
}
